// Indexer - the routable foundation. Routable reference files lead with a <!--icm--> metadata block
// (parsed/stripped by internal/meta). `ratchet reindex` scans the routable folders, reads those
// blocks, and regenerates manifest.json MECHANICALLY (no LLM summarization). `ratchet index` builds a
// per-KB routing index from file CONTENT (no blocks needed). Port of src.bak/Runtime/Indexer.cs.
package search

import (
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/scanset/Ratchet/internal/conventions"
	"github.com/scanset/Ratchet/internal/jsonx"
	"github.com/scanset/Ratchet/internal/meta"
	"github.com/scanset/Ratchet/internal/model"
)

var (
	kbTextExt  = map[string]bool{".md": true, ".markdown": true, ".txt": true, ".text": true}
	kbSkipDirs = map[string]bool{".index": true, ".git": true, "bin": true, "obj": true, "dist": true, "node_modules": true}
	stopWords  = toSet([]string{
		"the", "and", "for", "that", "this", "with", "from", "are", "was", "have", "has", "not", "but", "you", "your",
		"can", "will", "its", "use", "used", "using", "one", "two", "each", "when", "then", "into", "than", "also", "may",
		"must", "they", "them", "their", "there", "which", "what", "who", "how", "why", "all", "any", "some", "more"})
)

// manifest output shapes (field order matches the C# writer so regenerated files are byte-stable).
type reindexOut struct {
	Comment     string        `json:"$comment"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Domain      string        `json:"domain"`
	Entries     []model.Entry `json:"entries"`
}

type kbEntryOut struct {
	ID       string   `json:"id"`
	Title    string   `json:"title"`
	Path     string   `json:"path"`
	Summary  string   `json:"summary"`
	Keywords []string `json:"keywords"`
}

type kbManifestOut struct {
	Comment string       `json:"$comment"`
	Name    string       `json:"name"`
	Entries []kbEntryOut `json:"entries"`
}

func firstHeading(text string) string {
	for _, raw := range strings.Split(text, "\n") {
		line := strings.TrimSpace(raw)
		if strings.HasPrefix(line, "# ") {
			return strings.TrimSpace(line[2:])
		}
	}
	return ""
}

// Reindex scans the routable folders under root, reads each file's metadata block, and regenerates
// root/manifest.json. configName/configDomain seed the header when no existing manifest provides one.
// Returns the entry count written.
func Reindex(root, configName, configDomain string, status func(string)) int {
	if status == nil {
		status = func(string) {}
	}
	name, description, domain := configName, "", configDomain
	manifestPath := filepath.Join(root, conventions.ManifestFile)
	if data, err := os.ReadFile(manifestPath); err == nil {
		if old := jsonx.AsObject(parseOrNil(data)); old != nil {
			name = jsonx.GetStringOr(old, "name", name)
			description = jsonx.GetStringOr(old, "description", description)
			domain = jsonx.GetStringOr(old, "domain", domain)
		}
	}

	var entries []model.Entry
	for _, d := range conventions.RoutableDirs {
		dir := filepath.Join(root, d)
		st, err := os.Stat(dir)
		if err != nil || !st.IsDir() {
			continue
		}
		var files []string
		_ = filepath.Walk(dir, func(p string, info os.FileInfo, err error) error {
			if err == nil && !info.IsDir() && strings.EqualFold(filepath.Ext(p), ".md") {
				files = append(files, p)
			}
			return nil
		})
		sort.Slice(files, func(i, j int) bool { return strings.ToLower(files[i]) < strings.ToLower(files[j]) })
		for _, f := range files {
			fn := filepath.Base(f)
			if strings.EqualFold(fn, "README.md") {
				continue // folder guides
			}
			rel := relForward(root, f)
			under := fn
			if len(rel) > len(d) {
				under = rel[len(d)+1:] // path below the layer dir
			}
			group := ""
			if lastSlash := strings.LastIndex(under, "/"); lastSlash >= 0 {
				group = under[:lastSlash]
			}
			text, err := os.ReadFile(f)
			if err != nil {
				continue
			}
			m := meta.ExtractMeta(string(text))
			if m == nil {
				status("skip (no <!--icm--> block): " + rel)
				continue
			}
			defaultID := strings.ReplaceAll(strings.ReplaceAll(d+"/"+under, ".md", ""), "/", "-")
			e := model.Entry{
				ID:       jsonx.GetStringOr(m, "id", defaultID),
				Title:    jsonx.GetStringOr(m, "title", orStr(firstHeading(string(text)), jsonx.GetStringOr(m, "id", defaultID))),
				Path:     rel,
				Summary:  jsonx.GetStringOr(m, "summary", ""),
				DocType:  jsonx.GetStringOr(m, "doc_type", d),
				Group:    jsonx.GetStringOr(m, "group", group),
				Keywords: []string{},
			}
			for _, kw := range jsonx.GetArr(m, "keywords") {
				if kw != nil {
					e.Keywords = append(e.Keywords, toStr(kw))
				}
			}
			entries = append(entries, e)
		}
	}

	out := reindexOut{
		Comment: "Generated by `ratchet reindex` from each file's <!--icm--> metadata block. Edit the block in the source file, not this file.",
		Name:    name, Description: description, Domain: domain, Entries: entries,
	}
	_ = os.WriteFile(manifestPath, []byte(jsonx.SerializePretty(out)), 0o644)
	status("reindex: wrote " + strconv.Itoa(len(entries)) + " entries -> " + conventions.ManifestFile)
	return len(entries)
}

// BuildManifestEntries builds manifest entries for a KB directory from content: id from relpath,
// title from the first heading, summary from the first prose line, keywords from the top terms.
func BuildManifestEntries(dirAbs string) []model.Entry {
	var entries []model.Entry
	st, err := os.Stat(dirAbs)
	if dirAbs == "" || err != nil || !st.IsDir() {
		return entries
	}
	root, _ := filepath.Abs(dirAbs)
	buildWalk(root, root, &entries)
	return entries
}

func buildWalk(root, dir string, entries *[]model.Entry) {
	files, _ := os.ReadDir(dir)
	sort.Slice(files, func(i, j int) bool { return strings.ToLower(files[i].Name()) < strings.ToLower(files[j].Name()) })
	for _, f := range files {
		if f.IsDir() {
			continue
		}
		name := f.Name()
		if !kbTextExt[strings.ToLower(filepath.Ext(name))] {
			continue
		}
		if strings.EqualFold(name, conventions.ManifestFile) || strings.EqualFold(name, "README.md") {
			continue
		}
		full := filepath.Join(dir, name)
		data, err := os.ReadFile(full)
		if err != nil {
			continue
		}
		text := meta.StripMeta(string(data))
		rel := relForward(root, full)
		ext := filepath.Ext(rel)
		e := model.Entry{
			Path:     rel,
			ID:       strings.ReplaceAll(rel[:len(rel)-len(ext)], "/", "-"),
			Title:    orStr(firstHeading(text), strings.TrimSuffix(name, filepath.Ext(name))),
			Summary:  firstProse(text),
			Keywords: topTerms(text, 8),
		}
		*entries = append(*entries, e)
	}
	subs, _ := os.ReadDir(dir)
	sort.Slice(subs, func(i, j int) bool { return strings.ToLower(subs[i].Name()) < strings.ToLower(subs[j].Name()) })
	for _, s := range subs {
		if s.IsDir() && !kbSkipDirs[strings.ToLower(s.Name())] {
			buildWalk(root, filepath.Join(dir, s.Name()), entries)
		}
	}
}

func firstProse(text string) string {
	for _, raw := range strings.Split(text, "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "```") ||
			strings.HasPrefix(line, "<") || strings.HasPrefix(line, "|") {
			continue
		}
		if len(line) > 200 {
			return line[:200]
		}
		return line
	}
	return ""
}

func topTerms(text string, n int) []string {
	counts := map[string]int{}
	for _, w := range Tokens(text) {
		if len(w) < 4 || stopWords[w] {
			continue
		}
		counts[w]++
	}
	type kv struct {
		k string
		v int
	}
	list := make([]kv, 0, len(counts))
	for k, v := range counts {
		list = append(list, kv{k, v})
	}
	// stable by count desc; ties keep insertion-ish order via secondary key for determinism
	sort.SliceStable(list, func(i, j int) bool {
		if list[i].v != list[j].v {
			return list[i].v > list[j].v
		}
		return list[i].k < list[j].k
	})
	out := []string{}
	for i := 0; i < len(list) && len(out) < n; i++ {
		out = append(out, list[i].k)
	}
	return out
}

// WriteKbManifest writes <dirAbs>/manifest.json from content (the committed routing index for a KB
// library). Returns the entry count.
func WriteKbManifest(dirAbs string, status func(string)) int {
	if status == nil {
		status = func(string) {}
	}
	entries := BuildManifestEntries(dirAbs)
	outEntries := make([]kbEntryOut, 0, len(entries))
	for _, e := range entries {
		kws := e.Keywords
		if kws == nil {
			kws = []string{}
		}
		outEntries = append(outEntries, kbEntryOut{ID: e.ID, Title: e.Title, Path: e.Path, Summary: e.Summary, Keywords: kws})
	}
	name := filepath.Base(strings.TrimRight(mustAbs(dirAbs), `\/`))
	out := kbManifestOut{
		Comment: "Generated by `ratchet index` from file content - the routing index for this knowledge library.",
		Name:    name, Entries: outEntries,
	}
	outPath := filepath.Join(dirAbs, conventions.ManifestFile)
	_ = os.WriteFile(outPath, []byte(jsonx.SerializePretty(out)), 0o644)
	status("index: wrote " + strconv.Itoa(len(entries)) + " entries -> " + outPath)
	return len(entries)
}

// LoadManifestMap loads <dirAbs>/manifest.json into a path -> Entry map (empty if absent/unreadable).
func LoadManifestMap(dirAbs string) map[string]model.Entry {
	out := map[string]model.Entry{}
	p := filepath.Join(dirAbs, conventions.ManifestFile)
	m, err := model.LoadManifest(p)
	if err != nil {
		return out
	}
	for _, e := range m.Entries {
		out[e.Path] = e
	}
	return out
}

// --- small helpers ---

func relForward(root, full string) string {
	rel := strings.TrimLeft(strings.TrimPrefix(full, root), `\/`)
	return strings.ReplaceAll(rel, `\`, "/")
}

func parseOrNil(data []byte) any {
	v, err := jsonx.Parse(string(data))
	if err != nil {
		return nil
	}
	return v
}

func mustAbs(p string) string {
	abs, err := filepath.Abs(p)
	if err != nil {
		return p
	}
	return abs
}

func orStr(a, b string) string {
	if a != "" {
		return a
	}
	return b
}

func toSet(ss []string) map[string]bool {
	m := make(map[string]bool, len(ss))
	for _, s := range ss {
		m[s] = true
	}
	return m
}

func toStr(v any) string {
	if s, ok := v.(string); ok {
		return s
	}
	return ""
}
